name: Choreo

on:
  schedule:
    - cron: '3 */3 * * *'

jobs:
  Choreo:
    name: Choreo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 1
      - run: |
            echo $(date) > README.md
            git checkout --orphan tmp_work
            git branch -d main
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: choreo
          create_branch: true
          branch: main
          push_options: --force
      - uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 21600
